Algoritmo "semnome"
//Faça um programa para ler números do teclado até que o usuário digite o
//número 0. Quando encerrar o loop, deve ser escrito na tela uma mensagem
//“Sistema Encerrado”.
Var
   num: real

Inicio
 escreva("digite o numero:")
            leia(num)

      enquanto (num<>0) faca
               escreva("ERRO, tente novamente:")
               leia(num)
      fimenquanto
                 escreva("Sistema Encerrado")



Fimalgoritmo